# Generated by Django 5.0.6 on 2024-07-24 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_note_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
